<table class="table table-striped">
	<tr>
		<th>Date</th>
		<th>Sql</th>
		<th>Elapsed</th>
	</tr>
	<?php foreach ($this->list as $item): ?>
    	<tr>
    		<td style="white-space: nowrap;"><a href="<?= $this->url('lachesis/detail', ['project' => $this->project,'id' => $item->id]) ?>"><?= $item->start ?></a></td>
    		<td><?= $item->sql ?></td>
    		<td style="white-space: nowrap;"><?= $item->elapsed / 1000 ?> ms</td>
    	</tr>
	<?php endforeach; ?>
</table>