<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo $this->headTitle('Apigility');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->losHeadLink(array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')))
        ->prependBootstrap()
        ->appendStylesheet('/css/zeus.css');
        //->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
        //->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));
    echo $this->losHeadScript()
        //->appendChosen(true)
        ->prependBootstrap()
        ->prependJquery();
    /*echo $this->headScript()
        ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
        ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));*/
?>
    </head>
    <body>
    	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?php echo $this->url('home',[],true) ?>" class="navbar-brand">
                        Zeus
                    </a>
                </div>

                <div class="collapse navbar-collapse nav-navbar-collapse">
                    <ul class="nav navbar-nav navbar-admin">
                        <?php
                        $menu = $this->losNavigation('Navigation')->menu();
                        echo $menu;
                        ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-right" style="margin:0;">
                        <?= $this->selectProject(); ?>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->losIcon('glyphicon-user') ?> <span class="caret"></span></a>
                          <ul class="dropdown-menu" role="menu">
                          </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
